"""add_multi_tenant_and_multi_boq

Revision ID: 09eaa0b69dc9
Revises: 269645257591
Create Date: 2026-07-15 18:54:37.231744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
"""add_multi_tenant_and_multi_boq

Revision ID: 09eaa0b69dc9
Revises: 269645257591
Create Date: 2026-07-15 18:54:37.231744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09eaa0b69dc9'
down_revision: Union[str, Sequence[str], None] = '269645257591'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1. Create new tables
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('last_updated_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=False)
    op.create_table('boq_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('file_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('last_updated_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_boq_documents_file_hash'), 'boq_documents', ['file_hash'], unique=False)
    op.create_index(op.f('ix_boq_documents_id'), 'boq_documents', ['id'], unique=False)
    op.create_index(op.f('ix_boq_documents_name'), 'boq_documents', ['name'], unique=False)
    
    # 2. Add columns as nullable first
    op.add_column('boq_items', sa.Column('boq_id', sa.Integer(), nullable=True))
    op.add_column('projects', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'projects', 'companies', ['company_id'], ['id'], ondelete='CASCADE')

    # 3. Data Migration
    # Create default company
    op.execute("INSERT INTO companies (name) VALUES ('General')")
    # Update existing projects to belong to default company
    op.execute("UPDATE projects SET company_id = (SELECT MIN(id) FROM companies) WHERE company_id IS NULL")
    # Create default BOQ documents for existing projects
    op.execute("INSERT INTO boq_documents (project_id, name, file_hash) SELECT id, 'Main BOQ', 'default_import_' || id FROM projects")
    # Update boq_items to point to the newly created boq_documents
    op.execute("UPDATE boq_items SET boq_id = (SELECT id FROM boq_documents WHERE boq_documents.project_id = boq_items.project_id)")
    # Delete any dangling boq_items that didn't get mapped
    op.execute("DELETE FROM boq_items WHERE boq_id IS NULL")

    # 4. Enforce constraints and clean up columns
    op.alter_column('boq_items', 'boq_id', nullable=False)
    op.drop_constraint('boq_items_project_id_fkey', 'boq_items', type_='foreignkey')
    op.create_foreign_key(None, 'boq_items', 'boq_documents', ['boq_id'], ['id'], ondelete='CASCADE')
    op.drop_column('boq_items', 'project_id')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column('projects', 'company_id')
    op.add_column('boq_items', sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'boq_items', type_='foreignkey')
    op.create_foreign_key(op.f('boq_items_project_id_fkey'), 'boq_items', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_column('boq_items', 'boq_id')
    op.drop_index(op.f('ix_boq_documents_name'), table_name='boq_documents')
    op.drop_index(op.f('ix_boq_documents_id'), table_name='boq_documents')
    op.drop_index(op.f('ix_boq_documents_file_hash'), table_name='boq_documents')
    op.drop_table('boq_documents')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
