"""Add boq hierarchy and project metadata fields

Revision ID: 135cb4a84a08
Revises: 6f0996d28d47
Create Date: 2026-04-03 14:01:57.886774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '135cb4a84a08'
down_revision: Union[str, Sequence[str], None] = '6f0996d28d47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boq_items', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.add_column('boq_items', sa.Column('row_category', sa.String(), nullable=True))
    op.add_column('boq_items', sa.Column('hierarchy_level', sa.Integer(), nullable=True))
    op.add_column('boq_items', sa.Column('mapping_code', sa.String(), nullable=True))
    op.create_index(op.f('ix_boq_items_mapping_code'), 'boq_items', ['mapping_code'], unique=False)
    op.create_index(op.f('ix_boq_items_row_category'), 'boq_items', ['row_category'], unique=False)
    op.create_foreign_key(None, 'boq_items', 'boq_items', ['parent_id'], ['id'], ondelete='SET NULL')
    op.add_column('projects', sa.Column('client_name', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('report_date', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'report_date')
    op.drop_column('projects', 'client_name')
    op.drop_constraint(None, 'boq_items', type_='foreignkey')
    op.drop_index(op.f('ix_boq_items_row_category'), table_name='boq_items')
    op.drop_index(op.f('ix_boq_items_mapping_code'), table_name='boq_items')
    op.drop_column('boq_items', 'mapping_code')
    op.drop_column('boq_items', 'hierarchy_level')
    op.drop_column('boq_items', 'row_category')
    op.drop_column('boq_items', 'parent_id')
    # ### end Alembic commands ###
