"""add_project_integrations_and_sheet_row_index

Revision ID: 269645257591
Revises: 135cb4a84a08
Create Date: 2026-07-15 16:43:23.517249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '269645257591'
down_revision: Union[str, Sequence[str], None] = '135cb4a84a08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_integrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('spreadsheet_id', sa.String(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=False),
    sa.Column('sheet_name', sa.String(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('last_updated_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_integrations_id'), 'project_integrations', ['id'], unique=False)
    op.add_column('boq_items', sa.Column('sheet_row_index', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('boq_items', 'sheet_row_index')
    op.drop_index(op.f('ix_project_integrations_id'), table_name='project_integrations')
    op.drop_table('project_integrations')
    # ### end Alembic commands ###
