"""add_contract_hierarchy

Revision ID: 299cd1cf89bc
Revises: e4f5a6b7c8d9
Create Date: 2026-07-24 16:22:27.812077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '299cd1cf89bc'
down_revision: Union[str, Sequence[str], None] = 'e4f5a6b7c8d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('contract_type', sa.String(), nullable=False),
    sa.Column('contractor_name', sa.String(), nullable=True),
    sa.Column('contract_value', sa.Float(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('last_updated_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contracts_contract_type'), 'contracts', ['contract_type'], unique=False)
    op.create_index(op.f('ix_contracts_id'), 'contracts', ['id'], unique=False)
    op.create_index(op.f('ix_contracts_name'), 'contracts', ['name'], unique=False)
    op.add_column('boq_documents', sa.Column('contract_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_boq_documents_contract_id'), 'boq_documents', ['contract_id'], unique=False)
    op.create_foreign_key(None, 'boq_documents', 'contracts', ['contract_id'], ['id'], ondelete='CASCADE')
    op.add_column('budgets', sa.Column('contract_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_budgets_contract_id'), 'budgets', ['contract_id'], unique=False)
    op.create_foreign_key(None, 'budgets', 'contracts', ['contract_id'], ['id'], ondelete='CASCADE')
    op.add_column('documents', sa.Column('contract_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_documents_contract_id'), 'documents', ['contract_id'], unique=False)
    op.create_foreign_key(None, 'documents', 'contracts', ['contract_id'], ['id'], ondelete='CASCADE')
    op.add_column('ipcs', sa.Column('contract_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_ipcs_contract_id'), 'ipcs', ['contract_id'], unique=False)
    op.create_foreign_key(None, 'ipcs', 'contracts', ['contract_id'], ['id'], ondelete='CASCADE')
    op.add_column('notes', sa.Column('contract_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_notes_contract_id'), 'notes', ['contract_id'], unique=False)
    op.create_foreign_key(None, 'notes', 'contracts', ['contract_id'], ['id'], ondelete='CASCADE')
    op.add_column('project_integrations', sa.Column('contract_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_project_integrations_contract_id'), 'project_integrations', ['contract_id'], unique=False)
    op.create_foreign_key(None, 'project_integrations', 'contracts', ['contract_id'], ['id'], ondelete='CASCADE')

    # Data Seeding & Migration
    bind = op.get_bind()
    projects = bind.execute(sa.text("SELECT id FROM projects")).fetchall()
    
    for project in projects:
        project_id = project[0]
        
        # Insert default General Contract and retrieve its ID
        general_contract_id = bind.execute(sa.text(
            "INSERT INTO contracts (project_id, name, contract_type, status, created_at, updated_at) "
            "VALUES (:project_id, 'General Contract', 'GENERAL', 'active', NOW(), NOW()) RETURNING id"
        ), {"project_id": project_id}).scalar()
        
        # Seed the other 4 standard contract types under this project
        bind.execute(sa.text(
            "INSERT INTO contracts (project_id, name, contract_type, status, created_at, updated_at) VALUES "
            "(:project_id, 'Unit Price Contract', 'UNIT_PRICE', 'active', NOW(), NOW()),"
            "(:project_id, 'Lump Sum Contract', 'LUMP_SUM', 'active', NOW(), NOW()),"
            "(:project_id, 'Cost Plus Contract', 'COST_PLUS', 'active', NOW(), NOW()),"
            "(:project_id, 'Design & Build Contract', 'DESIGN_BUILD', 'active', NOW(), NOW())"
        ), {"project_id": project_id})
        
        # Move all existing records of this project to the newly created General Contract
        tables_to_update = ['boq_documents', 'budgets', 'documents', 'ipcs', 'notes', 'project_integrations']
        for table in tables_to_update:
            bind.execute(sa.text(
                f"UPDATE {table} SET contract_id = :contract_id WHERE project_id = :project_id"
            ), {"contract_id": general_contract_id, "project_id": project_id})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project_integrations', type_='foreignkey')
    op.drop_index(op.f('ix_project_integrations_contract_id'), table_name='project_integrations')
    op.drop_column('project_integrations', 'contract_id')
    op.drop_constraint(None, 'notes', type_='foreignkey')
    op.drop_index(op.f('ix_notes_contract_id'), table_name='notes')
    op.drop_column('notes', 'contract_id')
    op.drop_constraint(None, 'ipcs', type_='foreignkey')
    op.drop_index(op.f('ix_ipcs_contract_id'), table_name='ipcs')
    op.drop_column('ipcs', 'contract_id')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_index(op.f('ix_documents_contract_id'), table_name='documents')
    op.drop_column('documents', 'contract_id')
    op.drop_constraint(None, 'budgets', type_='foreignkey')
    op.drop_index(op.f('ix_budgets_contract_id'), table_name='budgets')
    op.drop_column('budgets', 'contract_id')
    op.drop_constraint(None, 'boq_documents', type_='foreignkey')
    op.drop_index(op.f('ix_boq_documents_contract_id'), table_name='boq_documents')
    op.drop_column('boq_documents', 'contract_id')
    op.drop_index(op.f('ix_contracts_name'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_id'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_contract_type'), table_name='contracts')
    op.drop_table('contracts')
    # ### end Alembic commands ###
