"""phase_1_database_decoupling

Revision ID: 30f424242f27
Revises: d198e9ccc4e8
Create Date: 2026-07-25 12:23:37.227037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '30f424242f27'
down_revision: Union[str, Sequence[str], None] = 'd198e9ccc4e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_schedule_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('file_url', sa.String(), nullable=True),
    sa.Column('file_type', sa.String(), nullable=True),
    sa.Column('origin', sa.String(), nullable=True),
    sa.Column('integration_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('last_updated_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['integration_id'], ['project_integrations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_schedule_documents_contract_id'), 'activity_schedule_documents', ['contract_id'], unique=False)
    op.create_index(op.f('ix_activity_schedule_documents_id'), 'activity_schedule_documents', ['id'], unique=False)
    op.create_index(op.f('ix_activity_schedule_documents_integration_id'), 'activity_schedule_documents', ['integration_id'], unique=False)
    op.create_index(op.f('ix_activity_schedule_documents_name'), 'activity_schedule_documents', ['name'], unique=False)
    op.create_table('budget_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('budget_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('file_url', sa.String(), nullable=True),
    sa.Column('file_type', sa.String(), nullable=True),
    sa.Column('origin', sa.String(), nullable=True),
    sa.Column('integration_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('last_updated_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['budget_id'], ['budgets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['integration_id'], ['project_integrations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_budget_documents_budget_id'), 'budget_documents', ['budget_id'], unique=False)
    op.create_index(op.f('ix_budget_documents_id'), 'budget_documents', ['id'], unique=False)
    op.create_index(op.f('ix_budget_documents_integration_id'), 'budget_documents', ['integration_id'], unique=False)
    op.create_index(op.f('ix_budget_documents_name'), 'budget_documents', ['name'], unique=False)
    op.create_table('field_ops_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('file_url', sa.String(), nullable=True),
    sa.Column('file_type', sa.String(), nullable=True),
    sa.Column('origin', sa.String(), nullable=True),
    sa.Column('integration_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('last_updated_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['integration_id'], ['project_integrations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_field_ops_documents_contract_id'), 'field_ops_documents', ['contract_id'], unique=False)
    op.create_index(op.f('ix_field_ops_documents_id'), 'field_ops_documents', ['id'], unique=False)
    op.create_index(op.f('ix_field_ops_documents_integration_id'), 'field_ops_documents', ['integration_id'], unique=False)
    op.create_index(op.f('ix_field_ops_documents_name'), 'field_ops_documents', ['name'], unique=False)
    op.create_table('ipc_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ipc_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('file_url', sa.String(), nullable=True),
    sa.Column('file_type', sa.String(), nullable=True),
    sa.Column('origin', sa.String(), nullable=True),
    sa.Column('integration_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('last_updated_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['integration_id'], ['project_integrations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ipc_id'], ['ipcs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ipc_documents_id'), 'ipc_documents', ['id'], unique=False)
    op.create_index(op.f('ix_ipc_documents_integration_id'), 'ipc_documents', ['integration_id'], unique=False)
    op.create_index(op.f('ix_ipc_documents_ipc_id'), 'ipc_documents', ['ipc_id'], unique=False)
    op.create_index(op.f('ix_ipc_documents_name'), 'ipc_documents', ['name'], unique=False)
    op.create_table('milestone_claim_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('file_url', sa.String(), nullable=True),
    sa.Column('file_type', sa.String(), nullable=True),
    sa.Column('origin', sa.String(), nullable=True),
    sa.Column('integration_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('last_updated_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['integration_id'], ['project_integrations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_milestone_claim_documents_contract_id'), 'milestone_claim_documents', ['contract_id'], unique=False)
    op.create_index(op.f('ix_milestone_claim_documents_id'), 'milestone_claim_documents', ['id'], unique=False)
    op.create_index(op.f('ix_milestone_claim_documents_integration_id'), 'milestone_claim_documents', ['integration_id'], unique=False)
    op.create_index(op.f('ix_milestone_claim_documents_name'), 'milestone_claim_documents', ['name'], unique=False)
    op.create_table('program_of_works_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('file_url', sa.String(), nullable=True),
    sa.Column('file_type', sa.String(), nullable=True),
    sa.Column('origin', sa.String(), nullable=True),
    sa.Column('integration_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('last_updated_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['integration_id'], ['project_integrations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_program_of_works_documents_contract_id'), 'program_of_works_documents', ['contract_id'], unique=False)
    op.create_index(op.f('ix_program_of_works_documents_id'), 'program_of_works_documents', ['id'], unique=False)
    op.create_index(op.f('ix_program_of_works_documents_integration_id'), 'program_of_works_documents', ['integration_id'], unique=False)
    op.create_index(op.f('ix_program_of_works_documents_name'), 'program_of_works_documents', ['name'], unique=False)
    op.create_table('rate_schedule_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('file_url', sa.String(), nullable=True),
    sa.Column('file_type', sa.String(), nullable=True),
    sa.Column('origin', sa.String(), nullable=True),
    sa.Column('integration_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('last_updated_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['integration_id'], ['project_integrations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rate_schedule_documents_contract_id'), 'rate_schedule_documents', ['contract_id'], unique=False)
    op.create_index(op.f('ix_rate_schedule_documents_id'), 'rate_schedule_documents', ['id'], unique=False)
    op.create_index(op.f('ix_rate_schedule_documents_integration_id'), 'rate_schedule_documents', ['integration_id'], unique=False)
    op.create_index(op.f('ix_rate_schedule_documents_name'), 'rate_schedule_documents', ['name'], unique=False)
    op.create_table('reimbursable_claim_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('file_url', sa.String(), nullable=True),
    sa.Column('file_type', sa.String(), nullable=True),
    sa.Column('origin', sa.String(), nullable=True),
    sa.Column('integration_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('last_updated_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['integration_id'], ['project_integrations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reimbursable_claim_documents_contract_id'), 'reimbursable_claim_documents', ['contract_id'], unique=False)
    op.create_index(op.f('ix_reimbursable_claim_documents_id'), 'reimbursable_claim_documents', ['id'], unique=False)
    op.create_index(op.f('ix_reimbursable_claim_documents_integration_id'), 'reimbursable_claim_documents', ['integration_id'], unique=False)
    op.create_index(op.f('ix_reimbursable_claim_documents_name'), 'reimbursable_claim_documents', ['name'], unique=False)
    op.create_table('tech_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('file_url', sa.String(), nullable=True),
    sa.Column('file_type', sa.String(), nullable=True),
    sa.Column('origin', sa.String(), nullable=True),
    sa.Column('integration_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('last_updated_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['integration_id'], ['project_integrations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tech_documents_contract_id'), 'tech_documents', ['contract_id'], unique=False)
    op.create_index(op.f('ix_tech_documents_id'), 'tech_documents', ['id'], unique=False)
    op.create_index(op.f('ix_tech_documents_integration_id'), 'tech_documents', ['integration_id'], unique=False)
    op.create_index(op.f('ix_tech_documents_name'), 'tech_documents', ['name'], unique=False)
    op.create_table('activity_schedule_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('activity_id', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('weight_percentage', sa.Float(), nullable=True),
    sa.Column('fixed_price', sa.Float(), nullable=True),
    sa.Column('values_map', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('last_updated_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['activity_schedule_documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['activity_schedule_items.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_schedule_items_activity_id'), 'activity_schedule_items', ['activity_id'], unique=False)
    op.create_index(op.f('ix_activity_schedule_items_id'), 'activity_schedule_items', ['id'], unique=False)
    op.create_table('field_ops_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('values_map', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('last_updated_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['field_ops_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_field_ops_items_id'), 'field_ops_items', ['id'], unique=False)
    op.create_table('milestone_claim_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('claim_number', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('amount_claimed', sa.Float(), nullable=True),
    sa.Column('amount_certified', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('values_map', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('last_updated_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['milestone_claim_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_milestone_claim_items_claim_number'), 'milestone_claim_items', ['claim_number'], unique=False)
    op.create_index(op.f('ix_milestone_claim_items_id'), 'milestone_claim_items', ['id'], unique=False)
    op.create_table('program_of_works_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('task_name', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('duration_days', sa.Integer(), nullable=True),
    sa.Column('percent_complete', sa.Float(), nullable=True),
    sa.Column('predecessors', sa.String(), nullable=True),
    sa.Column('values_map', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('last_updated_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['program_of_works_documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['program_of_works_items.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_program_of_works_items_id'), 'program_of_works_items', ['id'], unique=False)
    op.create_table('rate_schedule_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('resource_category', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('base_cost', sa.Float(), nullable=True),
    sa.Column('markup_percentage', sa.Float(), nullable=True),
    sa.Column('hourly_daily_rate', sa.Float(), nullable=True),
    sa.Column('values_map', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('last_updated_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['rate_schedule_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rate_schedule_items_id'), 'rate_schedule_items', ['id'], unique=False)
    op.create_index(op.f('ix_rate_schedule_items_resource_category'), 'rate_schedule_items', ['resource_category'], unique=False)
    op.create_table('reimbursable_claim_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.String(), nullable=True),
    sa.Column('supplier_name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('base_amount', sa.Float(), nullable=True),
    sa.Column('markup', sa.Float(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('values_map', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('last_updated_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['reimbursable_claim_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reimbursable_claim_items_id'), 'reimbursable_claim_items', ['id'], unique=False)
    op.create_index(op.f('ix_reimbursable_claim_items_invoice_number'), 'reimbursable_claim_items', ['invoice_number'], unique=False)
    op.create_table('tech_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('values_map', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('last_updated_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['tech_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tech_items_id'), 'tech_items', ['id'], unique=False)
    op.add_column('budgets', sa.Column('planned_value', sa.Float(), nullable=True))
    op.add_column('budgets', sa.Column('earned_value', sa.Float(), nullable=True))
    op.add_column('budgets', sa.Column('actual_cost', sa.Float(), nullable=True))
    op.add_column('budgets', sa.Column('values_map', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('documents', sa.Column('metadata_map', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_constraint(op.f('documents_budget_id_fkey'), 'documents', type_='foreignkey')
    op.drop_constraint(op.f('documents_ipc_id_fkey'), 'documents', type_='foreignkey')
    op.drop_column('documents', 'ipc_id')
    op.drop_column('documents', 'budget_id')
    op.add_column('ipcs', sa.Column('values_map', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('notes', sa.Column('values_map', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notes', 'values_map')
    op.drop_column('ipcs', 'values_map')
    op.add_column('documents', sa.Column('budget_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('ipc_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('documents_ipc_id_fkey'), 'documents', 'ipcs', ['ipc_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('documents_budget_id_fkey'), 'documents', 'budgets', ['budget_id'], ['id'], ondelete='SET NULL')
    op.drop_column('documents', 'metadata_map')
    op.drop_column('budgets', 'values_map')
    op.drop_column('budgets', 'actual_cost')
    op.drop_column('budgets', 'earned_value')
    op.drop_column('budgets', 'planned_value')
    op.drop_index(op.f('ix_tech_items_id'), table_name='tech_items')
    op.drop_table('tech_items')
    op.drop_index(op.f('ix_reimbursable_claim_items_invoice_number'), table_name='reimbursable_claim_items')
    op.drop_index(op.f('ix_reimbursable_claim_items_id'), table_name='reimbursable_claim_items')
    op.drop_table('reimbursable_claim_items')
    op.drop_index(op.f('ix_rate_schedule_items_resource_category'), table_name='rate_schedule_items')
    op.drop_index(op.f('ix_rate_schedule_items_id'), table_name='rate_schedule_items')
    op.drop_table('rate_schedule_items')
    op.drop_index(op.f('ix_program_of_works_items_id'), table_name='program_of_works_items')
    op.drop_table('program_of_works_items')
    op.drop_index(op.f('ix_milestone_claim_items_id'), table_name='milestone_claim_items')
    op.drop_index(op.f('ix_milestone_claim_items_claim_number'), table_name='milestone_claim_items')
    op.drop_table('milestone_claim_items')
    op.drop_index(op.f('ix_field_ops_items_id'), table_name='field_ops_items')
    op.drop_table('field_ops_items')
    op.drop_index(op.f('ix_activity_schedule_items_id'), table_name='activity_schedule_items')
    op.drop_index(op.f('ix_activity_schedule_items_activity_id'), table_name='activity_schedule_items')
    op.drop_table('activity_schedule_items')
    op.drop_index(op.f('ix_tech_documents_name'), table_name='tech_documents')
    op.drop_index(op.f('ix_tech_documents_integration_id'), table_name='tech_documents')
    op.drop_index(op.f('ix_tech_documents_id'), table_name='tech_documents')
    op.drop_index(op.f('ix_tech_documents_contract_id'), table_name='tech_documents')
    op.drop_table('tech_documents')
    op.drop_index(op.f('ix_reimbursable_claim_documents_name'), table_name='reimbursable_claim_documents')
    op.drop_index(op.f('ix_reimbursable_claim_documents_integration_id'), table_name='reimbursable_claim_documents')
    op.drop_index(op.f('ix_reimbursable_claim_documents_id'), table_name='reimbursable_claim_documents')
    op.drop_index(op.f('ix_reimbursable_claim_documents_contract_id'), table_name='reimbursable_claim_documents')
    op.drop_table('reimbursable_claim_documents')
    op.drop_index(op.f('ix_rate_schedule_documents_name'), table_name='rate_schedule_documents')
    op.drop_index(op.f('ix_rate_schedule_documents_integration_id'), table_name='rate_schedule_documents')
    op.drop_index(op.f('ix_rate_schedule_documents_id'), table_name='rate_schedule_documents')
    op.drop_index(op.f('ix_rate_schedule_documents_contract_id'), table_name='rate_schedule_documents')
    op.drop_table('rate_schedule_documents')
    op.drop_index(op.f('ix_program_of_works_documents_name'), table_name='program_of_works_documents')
    op.drop_index(op.f('ix_program_of_works_documents_integration_id'), table_name='program_of_works_documents')
    op.drop_index(op.f('ix_program_of_works_documents_id'), table_name='program_of_works_documents')
    op.drop_index(op.f('ix_program_of_works_documents_contract_id'), table_name='program_of_works_documents')
    op.drop_table('program_of_works_documents')
    op.drop_index(op.f('ix_milestone_claim_documents_name'), table_name='milestone_claim_documents')
    op.drop_index(op.f('ix_milestone_claim_documents_integration_id'), table_name='milestone_claim_documents')
    op.drop_index(op.f('ix_milestone_claim_documents_id'), table_name='milestone_claim_documents')
    op.drop_index(op.f('ix_milestone_claim_documents_contract_id'), table_name='milestone_claim_documents')
    op.drop_table('milestone_claim_documents')
    op.drop_index(op.f('ix_ipc_documents_name'), table_name='ipc_documents')
    op.drop_index(op.f('ix_ipc_documents_ipc_id'), table_name='ipc_documents')
    op.drop_index(op.f('ix_ipc_documents_integration_id'), table_name='ipc_documents')
    op.drop_index(op.f('ix_ipc_documents_id'), table_name='ipc_documents')
    op.drop_table('ipc_documents')
    op.drop_index(op.f('ix_field_ops_documents_name'), table_name='field_ops_documents')
    op.drop_index(op.f('ix_field_ops_documents_integration_id'), table_name='field_ops_documents')
    op.drop_index(op.f('ix_field_ops_documents_id'), table_name='field_ops_documents')
    op.drop_index(op.f('ix_field_ops_documents_contract_id'), table_name='field_ops_documents')
    op.drop_table('field_ops_documents')
    op.drop_index(op.f('ix_budget_documents_name'), table_name='budget_documents')
    op.drop_index(op.f('ix_budget_documents_integration_id'), table_name='budget_documents')
    op.drop_index(op.f('ix_budget_documents_id'), table_name='budget_documents')
    op.drop_index(op.f('ix_budget_documents_budget_id'), table_name='budget_documents')
    op.drop_table('budget_documents')
    op.drop_index(op.f('ix_activity_schedule_documents_name'), table_name='activity_schedule_documents')
    op.drop_index(op.f('ix_activity_schedule_documents_integration_id'), table_name='activity_schedule_documents')
    op.drop_index(op.f('ix_activity_schedule_documents_id'), table_name='activity_schedule_documents')
    op.drop_index(op.f('ix_activity_schedule_documents_contract_id'), table_name='activity_schedule_documents')
    op.drop_table('activity_schedule_documents')
    # ### end Alembic commands ###
