"""add_sheet_id_sheet_name_boq_name

Revision ID: 3e81ed97b41a
Revises: 09eaa0b69dc9
Create Date: 2026-07-16 14:49:20.402398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e81ed97b41a'
down_revision: Union[str, Sequence[str], None] = '09eaa0b69dc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boq_items', sa.Column('sheet_id', sa.String(), nullable=True))
    op.add_column('boq_items', sa.Column('sheet_name', sa.String(), nullable=True))
    op.add_column('project_integrations', sa.Column('boq_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_integrations', 'boq_name')
    op.drop_column('boq_items', 'sheet_name')
    op.drop_column('boq_items', 'sheet_id')
    # ### end Alembic commands ###
