"""IPC universal architecture upgrade

Revision ID: 43011c7ff2b5
Revises: 30f424242f27
Create Date: 2026-07-25 19:12:10.375524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43011c7ff2b5'
down_revision: Union[str, Sequence[str], None] = '30f424242f27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('revised_contract_value', sa.Float(), nullable=True))
    op.add_column('contracts', sa.Column('retention_rate', sa.Float(), nullable=True))
    op.add_column('contracts', sa.Column('max_retention_limit', sa.Float(), nullable=True))
    op.add_column('contracts', sa.Column('vat_rate', sa.Float(), nullable=True))
    op.add_column('contracts', sa.Column('withholding_tax_rate', sa.Float(), nullable=True))
    op.add_column('contracts', sa.Column('withholding_vat_rate', sa.String(), nullable=True))
    op.add_column('contracts', sa.Column('advance_payment_amount', sa.Float(), nullable=True))
    op.alter_column('ipc_documents', 'ipc_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_ipc_documents_cloud_file_id'), 'ipc_documents', ['cloud_file_id'], unique=False)
    op.create_index(op.f('ix_ipc_documents_contract_id'), 'ipc_documents', ['contract_id'], unique=False)
    op.create_index(op.f('ix_ipc_documents_project_id'), 'ipc_documents', ['project_id'], unique=False)
    op.add_column('ipcs', sa.Column('period_start', sa.Date(), nullable=True))
    op.add_column('ipcs', sa.Column('period_end', sa.Date(), nullable=True))
    op.add_column('ipcs', sa.Column('valuation_date', sa.Date(), nullable=True))
    op.add_column('ipcs', sa.Column('gross_amount_claimed', sa.Float(), nullable=True))
    op.add_column('ipcs', sa.Column('gross_amount_certified', sa.Float(), nullable=True))
    op.add_column('ipcs', sa.Column('total_deductions', sa.Float(), nullable=True))
    op.add_column('ipcs', sa.Column('net_amount_due', sa.Float(), nullable=True))
    op.add_column('ipcs', sa.Column('cumulative_certified', sa.Float(), nullable=True))
    op.add_column('ipcs', sa.Column('payment_status', sa.String(), server_default='UNPAID', nullable=False))
    op.add_column('ipcs', sa.Column('unpaid_amount', sa.Float(), nullable=True))
    op.add_column('ipcs', sa.Column('payment_date', sa.Date(), nullable=True))
    op.add_column('ipcs', sa.Column('payment_reference', sa.String(), nullable=True))
    op.drop_column('ipcs', 'amount_claimed')
    op.drop_column('ipcs', 'date_issued')
    op.drop_column('ipcs', 'amount_certified')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ipcs', sa.Column('amount_certified', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('ipcs', sa.Column('date_issued', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('ipcs', sa.Column('amount_claimed', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('ipcs', 'payment_reference')
    op.drop_column('ipcs', 'payment_date')
    op.drop_column('ipcs', 'unpaid_amount')
    op.drop_column('ipcs', 'payment_status')
    op.drop_column('ipcs', 'cumulative_certified')
    op.drop_column('ipcs', 'net_amount_due')
    op.drop_column('ipcs', 'total_deductions')
    op.drop_column('ipcs', 'gross_amount_certified')
    op.drop_column('ipcs', 'gross_amount_claimed')
    op.drop_column('ipcs', 'valuation_date')
    op.drop_column('ipcs', 'period_end')
    op.drop_column('ipcs', 'period_start')
    op.drop_index(op.f('ix_ipc_documents_project_id'), table_name='ipc_documents')
    op.drop_index(op.f('ix_ipc_documents_contract_id'), table_name='ipc_documents')
    op.drop_index(op.f('ix_ipc_documents_cloud_file_id'), table_name='ipc_documents')
    op.alter_column('ipc_documents', 'ipc_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('contracts', 'advance_payment_amount')
    op.drop_column('contracts', 'withholding_vat_rate')
    op.drop_column('contracts', 'withholding_tax_rate')
    op.drop_column('contracts', 'vat_rate')
    op.drop_column('contracts', 'max_retention_limit')
    op.drop_column('contracts', 'retention_rate')
    op.drop_column('contracts', 'revised_contract_value')
    # ### end Alembic commands ###
