"""update_milestone_claim_schema

Revision ID: be384199014b
Revises: e20fe681a3c7
Create Date: 2026-08-17 16:53:18.023061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'be384199014b'
down_revision: Union[str, Sequence[str], None] = 'e20fe681a3c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_boq_references', sa.Column('created_by', sa.String(), nullable=True))
    op.add_column('analysis_boq_references', sa.Column('last_updated_by', sa.String(), nullable=True))
    op.create_index(op.f('ix_analysis_boq_references_id'), 'analysis_boq_references', ['id'], unique=False)
    op.create_index(op.f('ix_analysis_boq_references_reference_source_id'), 'analysis_boq_references', ['reference_source_id'], unique=False)
    op.add_column('analysis_schedule_references', sa.Column('created_by', sa.String(), nullable=True))
    op.add_column('analysis_schedule_references', sa.Column('last_updated_by', sa.String(), nullable=True))
    op.create_index(op.f('ix_analysis_schedule_references_id'), 'analysis_schedule_references', ['id'], unique=False)
    op.create_index(op.f('ix_analysis_schedule_references_reference_source_id'), 'analysis_schedule_references', ['reference_source_id'], unique=False)
    op.add_column('milestone_claim_documents', sa.Column('gross_amount_claimed', sa.Float(), nullable=True))
    op.add_column('milestone_claim_documents', sa.Column('retention_deducted', sa.Float(), nullable=True))
    op.add_column('milestone_claim_documents', sa.Column('net_amount_due', sa.Float(), nullable=True))
    op.add_column('milestone_claim_documents', sa.Column('status', sa.String(), nullable=True))
    op.add_column('milestone_claim_documents', sa.Column('payment_status', sa.String(), nullable=True))
    op.add_column('milestone_claim_documents', sa.Column('values_map', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('milestone_claim_items', sa.Column('activity_id', sa.String(), nullable=True))
    op.add_column('milestone_claim_items', sa.Column('percentage_complete_this_period', sa.Float(), nullable=True))
    op.add_column('milestone_claim_items', sa.Column('amount_claimed_this_period', sa.Float(), nullable=True))
    op.drop_index(op.f('ix_milestone_claim_items_claim_number'), table_name='milestone_claim_items')
    op.create_index(op.f('ix_milestone_claim_items_activity_id'), 'milestone_claim_items', ['activity_id'], unique=False)
    op.drop_column('milestone_claim_items', 'amount_claimed')
    op.drop_column('milestone_claim_items', 'claim_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('milestone_claim_items', sa.Column('claim_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('milestone_claim_items', sa.Column('amount_claimed', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_milestone_claim_items_activity_id'), table_name='milestone_claim_items')
    op.create_index(op.f('ix_milestone_claim_items_claim_number'), 'milestone_claim_items', ['claim_number'], unique=False)
    op.drop_column('milestone_claim_items', 'amount_claimed_this_period')
    op.drop_column('milestone_claim_items', 'percentage_complete_this_period')
    op.drop_column('milestone_claim_items', 'activity_id')
    op.drop_column('milestone_claim_documents', 'values_map')
    op.drop_column('milestone_claim_documents', 'payment_status')
    op.drop_column('milestone_claim_documents', 'status')
    op.drop_column('milestone_claim_documents', 'net_amount_due')
    op.drop_column('milestone_claim_documents', 'retention_deducted')
    op.drop_column('milestone_claim_documents', 'gross_amount_claimed')
    op.drop_index(op.f('ix_analysis_schedule_references_reference_source_id'), table_name='analysis_schedule_references')
    op.drop_index(op.f('ix_analysis_schedule_references_id'), table_name='analysis_schedule_references')
    op.drop_column('analysis_schedule_references', 'last_updated_by')
    op.drop_column('analysis_schedule_references', 'created_by')
    op.drop_index(op.f('ix_analysis_boq_references_reference_source_id'), table_name='analysis_boq_references')
    op.drop_index(op.f('ix_analysis_boq_references_id'), table_name='analysis_boq_references')
    op.drop_column('analysis_boq_references', 'last_updated_by')
    op.drop_column('analysis_boq_references', 'created_by')
    # ### end Alembic commands ###
