"""add_headers_and_values_map

Revision ID: d0601b1af8a4
Revises: 3e81ed97b41a
Create Date: 2026-07-16 15:33:11.708585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd0601b1af8a4'
down_revision: Union[str, Sequence[str], None] = '3e81ed97b41a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boq_documents', sa.Column('headers', sa.JSON(), nullable=True))
    op.add_column('boq_items', sa.Column('values_map', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('boq_items', 'values_map')
    op.drop_column('boq_documents', 'headers')
    # ### end Alembic commands ###
