"""add_module_to_project_integrations

Revision ID: d198e9ccc4e8
Revises: 299cd1cf89bc
Create Date: 2026-07-24 17:53:36.144707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd198e9ccc4e8'
down_revision: Union[str, Sequence[str], None] = '299cd1cf89bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_integrations', sa.Column('module', sa.String(), server_default='boq', nullable=False))
    
    # Backfill module data based on existing document links
    op.execute("""
        UPDATE project_integrations 
        SET module = 'ipc' 
        WHERE id IN (SELECT integration_id FROM documents WHERE integration_id IS NOT NULL AND ipc_id IS NOT NULL)
    """)
    op.execute("""
        UPDATE project_integrations 
        SET module = 'budget' 
        WHERE id IN (SELECT integration_id FROM documents WHERE integration_id IS NOT NULL AND budget_id IS NOT NULL)
    """)
    op.execute("""
        UPDATE project_integrations p
        SET module = LOWER(d.department)
        FROM documents d
        WHERE p.id = d.integration_id AND d.department IS NOT NULL AND d.ipc_id IS NULL AND d.budget_id IS NULL
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_integrations', 'module')
    # ### end Alembic commands ###
