"""add meta_data to project_integrations

Revision ID: e20fe681a3c7
Revises: d34eb6d8e55e
Create Date: 2026-08-01 11:38:55.336699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e20fe681a3c7'
down_revision: Union[str, Sequence[str], None] = 'd34eb6d8e55e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notes', 'is_issue',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_column('notes', 'is_flagged_issue')
    op.add_column('project_integrations', sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_integrations', 'meta_data')
    op.add_column('notes', sa.Column('is_flagged_issue', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.alter_column('notes', 'is_issue',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###
